name: Terraform piepline

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Select Terraform action"
        required: true
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: iac/module-wise-iac/main

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show selected pipeline
        run: |
          echo "Selected pepeline:"
          echo "${{github.event.inputs.pipeline }}"

      - name: Run Plan
        if: github.event.inputs.pipeline == 'plan'
        run: echo "Running Terraform plan"

      - name: Run Apply
        if: github.event.inputs.pipeline == 'apply'
        run: echo "Running Terraform apply"

      - name: Run Destroy
        if: github.event.inputs.pipeline == 'destroy'
        run: echo "Running Terraform destroy"